// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMFzcLy2ALlYy5wwV6DnGbsSGLOzj6h7U',
    appId: '1:90497417959:web:5f5e34e06256891b575842',
    messagingSenderId: '90497417959',
    projectId: 'flutterauth-bb930',
    authDomain: 'flutterauth-bb930.firebaseapp.com',
    storageBucket: 'flutterauth-bb930.firebasestorage.app',
    measurementId: 'G-FXR8K83QRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWUrpnWx_Qr1R9r4r5Y5W3KTDeq1oJCXg',
    appId: '1:90497417959:android:158ba2bdb35dadd5575842',
    messagingSenderId: '90497417959',
    projectId: 'flutterauth-bb930',
    storageBucket: 'flutterauth-bb930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC07Bi3tUhyRee4DHJrjSkFuIVdp3KhpQE',
    appId: '1:90497417959:ios:07c77d78e599a9f1575842',
    messagingSenderId: '90497417959',
    projectId: 'flutterauth-bb930',
    storageBucket: 'flutterauth-bb930.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC07Bi3tUhyRee4DHJrjSkFuIVdp3KhpQE',
    appId: '1:90497417959:ios:07c77d78e599a9f1575842',
    messagingSenderId: '90497417959',
    projectId: 'flutterauth-bb930',
    storageBucket: 'flutterauth-bb930.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMFzcLy2ALlYy5wwV6DnGbsSGLOzj6h7U',
    appId: '1:90497417959:web:43523cf57b70804b575842',
    messagingSenderId: '90497417959',
    projectId: 'flutterauth-bb930',
    authDomain: 'flutterauth-bb930.firebaseapp.com',
    storageBucket: 'flutterauth-bb930.firebasestorage.app',
    measurementId: 'G-JSJNSTEW8T',
  );
}
